// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBbhisqTwG4i7uQ_jAL08UxS1rGi8abkS0',
    appId: '1:1008331623633:web:209c47acb01a7cb34f89f0',
    messagingSenderId: '1008331623633',
    projectId: 'authenticityassurance',
    authDomain: 'authenticityassurance.firebaseapp.com',
    storageBucket: 'authenticityassurance.firebasestorage.app',
    measurementId: 'G-2LH8ZYRJYS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBakf4vTFP3WrIByoMBvjv1f0p4xhTR0ao',
    appId: '1:1008331623633:android:ac4a8a748366f6fb4f89f0',
    messagingSenderId: '1008331623633',
    projectId: 'authenticityassurance',
    storageBucket: 'authenticityassurance.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGfQ-_q8f5En386z7dPfcZQCamIm8lxDc',
    appId: '1:1008331623633:ios:b878771755e53c784f89f0',
    messagingSenderId: '1008331623633',
    projectId: 'authenticityassurance',
    storageBucket: 'authenticityassurance.firebasestorage.app',
    iosBundleId: 'com.example.authenticity.authenticityassurance',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAGfQ-_q8f5En386z7dPfcZQCamIm8lxDc',
    appId: '1:1008331623633:ios:b878771755e53c784f89f0',
    messagingSenderId: '1008331623633',
    projectId: 'authenticityassurance',
    storageBucket: 'authenticityassurance.firebasestorage.app',
    iosBundleId: 'com.example.authenticity.authenticityassurance',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBbhisqTwG4i7uQ_jAL08UxS1rGi8abkS0',
    appId: '1:1008331623633:web:77efb1182b0dd9854f89f0',
    messagingSenderId: '1008331623633',
    projectId: 'authenticityassurance',
    authDomain: 'authenticityassurance.firebaseapp.com',
    storageBucket: 'authenticityassurance.firebasestorage.app',
    measurementId: 'G-WM46KJ0W55',
  );
}
